package tk.diamondbuildz.mod.character.reference;

import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;
import tk.diamondbuildz.mod.character.item.ItemBase;
import tk.diamondbuildz.mod.character.item.ItemChisel;
import tk.diamondbuildz.mod.character.item.ItemGlassCutter;
import tk.diamondbuildz.mod.character.item.ItemWithReturn;
import tk.diamondbuildz.mod.character.util.InjectionUtil;

import static tk.diamondbuildz.mod.character.util.InjectionUtil.Null;

/**
 * {@link Item} Instances class
 * All Items will be public static final and with null as their value to be filled with @ObjectHolder
 * {@link InjectionUtil#Null()} returns a null value and suppresses 'Argument might be null' generated by IntelliJ's IDEA
 *
 * @author Diamond
 */
@GameRegistry.ObjectHolder(Reference.MOD_ID)
public class ModItems {

    // Glass Shards
    public static final ItemBase GLASS_SHARD_CLEAR = Null();
    public static final ItemBase GLASS_SHARD_BLACK = Null();
    public static final ItemBase GLASS_SHARD_BROWN = Null();
    public static final ItemBase GLASS_SHARD_CYAN = Null();
    public static final ItemBase GLASS_SHARD_GRAY = Null();
    public static final ItemBase GLASS_SHARD_GREEN = Null();
    public static final ItemBase GLASS_SHARD_BLUE = Null();
    public static final ItemBase GLASS_SHARD_LIGHT_BLUE = Null();
    public static final ItemBase GLASS_SHARD_LIME = Null();
    public static final ItemBase GLASS_SHARD_MAGENTA = Null();
    public static final ItemBase GLASS_SHARD_ORANGE = Null();
    public static final ItemBase GLASS_SHARD_PINK = Null();
    public static final ItemBase GLASS_SHARD_PURPLE = Null();
    public static final ItemBase GLASS_SHARD_RED = Null();
    public static final ItemBase GLASS_SHARD_SILVER = Null();
    public static final ItemBase GLASS_SHARD_WHITE = Null();
    public static final ItemBase GLASS_SHARD_YELLOW = Null();

    // Molds
    public static final ItemWithReturn MOLD_A = Null();
    public static final ItemWithReturn MOLD_B = Null();
    public static final ItemWithReturn MOLD_C = Null();
    public static final ItemWithReturn MOLD_D = Null();
    public static final ItemWithReturn MOLD_E = Null();
    public static final ItemWithReturn MOLD_F = Null();
    public static final ItemWithReturn MOLD_G = Null();
    public static final ItemWithReturn MOLD_H = Null();
    public static final ItemWithReturn MOLD_I = Null();
    public static final ItemWithReturn MOLD_J = Null();
    public static final ItemWithReturn MOLD_K = Null();
    public static final ItemWithReturn MOLD_L = Null();
    public static final ItemWithReturn MOLD_M = Null();
    public static final ItemWithReturn MOLD_N = Null();
    public static final ItemWithReturn MOLD_O = Null();
    public static final ItemWithReturn MOLD_P = Null();
    public static final ItemWithReturn MOLD_Q = Null();
    public static final ItemWithReturn MOLD_R = Null();
    public static final ItemWithReturn MOLD_S = Null();
    public static final ItemWithReturn MOLD_T = Null();
    public static final ItemWithReturn MOLD_U = Null();
    public static final ItemWithReturn MOLD_V = Null();
    public static final ItemWithReturn MOLD_W = Null();
    public static final ItemWithReturn MOLD_X = Null();
    public static final ItemWithReturn MOLD_Y = Null();
    public static final ItemWithReturn MOLD_Z = Null();

    // Tools
    public static final ItemGlassCutter CUTTER_GLASS_DIAMOND = Null();
    public static final ItemGlassCutter CUTTER_GLASS_GOLD = Null();
    public static final ItemGlassCutter CUTTER_GLASS_IRON = Null();

    public static final ItemChisel CHISEL_DIAMOND = Null();
    public static final ItemChisel CHISEL_GOLD = Null();
    public static final ItemChisel CHISEL_IRON = Null();
}